# Generated by Django 5.2.1 on 2025-07-22 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('recipient', models.CharField(help_text='Email address or phone number', max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Email subject or SMS title', max_length=255)),
                ('message', models.TextField(help_text='Email body or SMS message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if notification failed')),
                ('retry_count', models.IntegerField(default=0)),
                ('external_id', models.CharField(blank=True, help_text='ID from external service (Twilio, SendGrid, etc.)', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like template used, campaign info, etc.')),
                ('sent_by', models.ForeignKey(blank=True, help_text='User who triggered the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type', 'status'], name='account_not_notific_39fed1_idx'), models.Index(fields=['recipient'], name='account_not_recipie_6cbaac_idx'), models.Index(fields=['created_at'], name='account_not_created_e61ece_idx'), models.Index(fields=['sent_by'], name='account_not_sent_by_1347c9_idx')],
            },
        ),
    ]
