# Generated by Django 5.2.1 on 2025-05-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0002_familypatient_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrative', 'Administrative'), ('Patient', 'Patient'), ('Coordinator', 'Coordinator'), ('Family Patient', 'Family Patient'), ('Social Assistant', 'Social Assistant'), ('Provider', 'Provider'), ('Administrator', 'Administrator')], max_length=20, null=True),
        ),
    ]
