# Generated by Django 5.2.1 on 2025-06-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfolder',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CareLink.service'),
        ),
    ]
