# Generated by Django 5.2.1 on 2025-06-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0004_medicalfolder_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedemand',
            options={'ordering': ['-created_at', 'priority'], 'verbose_name': 'Service Demand', 'verbose_name_plural': 'Service Demands'},
        ),
        migrations.RenameField(
            model_name='servicedemand',
            old_name='manage_by',
            new_name='managed_by',
        ),
        migrations.RemoveField(
            model_name='servicedemand',
            name='contact',
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CareLink.provider'),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='contact_method',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone Call'), ('Video Call', 'Video Call'), ('In Person', 'In Person'), ('SMS', 'SMS')], default='Email', max_length=20),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='coordinator_notes',
            field=models.TextField(blank=True, help_text='Internal notes from coordinators', null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the service needed'),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='duration_weeks',
            field=models.IntegerField(blank=True, help_text='How many weeks is this service needed?', null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='preferred_start_date',
            field=models.DateField(blank=True, help_text='When should the service start?', null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='preferred_time',
            field=models.CharField(blank=True, help_text='Preferred time of day (e.g., Morning, Afternoon, Evening)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Medical reason or justification for the service'),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Any special instructions or requirements', null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='title',
            field=models.CharField(default='Service Request', help_text='Brief title for the service request', max_length=200),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicedemand',
            name='frequency',
            field=models.CharField(choices=[('Once', 'One-time service'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly'), ('As needed', 'As needed')], default='Once', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicedemand',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
