# Generated by Django 5.2 on 2025-06-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0005_alter_servicedemand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
