# Generated by Django 5.2.1 on 2025-06-05 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0006_timeslot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
