# Generated by Django 5.2.1 on 2025-06-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0008_add_created_at_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='additional_data',
            field=models.JSONField(blank=True, help_text='Additional context data in JSON format', null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='affected_patient_id',
            field=models.BigIntegerField(blank=True, help_text='ID of affected patient', null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='affected_patient_name',
            field=models.CharField(blank=True, help_text='Name of affected patient', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='affected_provider_id',
            field=models.BigIntegerField(blank=True, help_text='ID of affected provider', null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='affected_provider_name',
            field=models.CharField(blank=True, help_text='Name of affected provider', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the action', null=True),
        ),
    ]
