# Generated by Django 5.2.1 on 2025-06-16 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0011_add_internal_note_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfolder',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this medical note', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
