# Generated by Django 5.2.1 on 2025-06-21 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0012_medicalfolder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(blank=True, help_text='Anonymous identifier for non-logged users', max_length=64, null=True)),
                ('consent_version', models.CharField(default='1.0', max_length=10)),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('essential_cookies', models.BooleanField(default=True, help_text='Always true for healthcare functionality')),
                ('analytics_cookies', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], default='denied', max_length=10)),
                ('marketing_cookies', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], default='denied', max_length=10)),
                ('functional_cookies', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], default='denied', max_length=10)),
                ('user_agent_snippet', models.CharField(blank=True, help_text='First 100 chars of user agent for audit', max_length=100, null=True)),
                ('page_url', models.URLField(blank=True, help_text='Page where consent was given', null=True)),
                ('ip_address_stored', models.BooleanField(default=False, help_text='Always False - IP not stored for privacy')),
                ('consent_method', models.CharField(choices=[('banner', 'Cookie Banner'), ('settings', 'Settings Page')], default='banner', max_length=20)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cookie Consent',
                'verbose_name_plural': 'Cookie Consents',
                'ordering': ['-consent_timestamp'],
                'indexes': [models.Index(fields=['user', '-consent_timestamp'], name='CareLink_co_user_id_344be5_idx'), models.Index(fields=['user_identifier', '-consent_timestamp'], name='CareLink_co_user_id_aa4e05_idx')],
            },
        ),
    ]
