# Generated by Django 5.2.1 on 2025-06-27 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0015_providerabsence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderShortAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('absence_type', models.CharField(choices=[('meal', 'Meal Break'), ('training', 'Training'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_short_absences', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_absences', to='CareLink.provider')),
            ],
            options={
                'verbose_name': 'Provider Short Absence',
                'verbose_name_plural': 'Provider Short Absences',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
