# Generated by Django 5.2.1 on 2025-06-28 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0016_providershortabsence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('team_assignment', models.CharField(choices=[('Coordinator', 'Coordinator Team'), ('Administrator', 'Administrator Team')], help_text='Default team assignment for this category', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnhancedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for the ticket', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the issue or request')),
                ('category', models.CharField(choices=[('Technical Issue', 'Technical Issue'), ('Care Request', 'Care Request'), ('Planning Issue', 'Planning Issue'), ('Billing Issue', 'Billing Issue'), ('Appointment Issue', 'Appointment Issue'), ('General Inquiry', 'General Inquiry'), ('Emergency', 'Emergency'), ('Other', 'Other')], default='General Inquiry', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('assigned_team', models.CharField(choices=[('Coordinator', 'Coordinator Team'), ('Administrator', 'Administrator Team')], help_text='Team responsible for handling this ticket', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark as urgent for immediate attention')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes visible only to team members', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Specific team member assigned to this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enhanced_tickets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enhanced Ticket',
                'verbose_name_plural': 'Enhanced Tickets',
                'ordering': ['-created_at', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Comment content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment visible only to team members')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CareLink.enhancedticket')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the status change', null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='CareLink.enhancedticket')),
            ],
            options={
                'verbose_name': 'Ticket Status History',
                'verbose_name_plural': 'Ticket Status History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enhancedticket',
            index=models.Index(fields=['status', 'priority'], name='CareLink_en_status_20184c_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedticket',
            index=models.Index(fields=['assigned_team', 'status'], name='CareLink_en_assigne_f97aef_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedticket',
            index=models.Index(fields=['created_by', 'status'], name='CareLink_en_created_1df0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedticket',
            index=models.Index(fields=['assigned_to', 'status'], name='CareLink_en_assigne_41a163_idx'),
        ),
    ]
