# Generated by Django 5.2.1 on 2025-07-05 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0019_add_account_lockout_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Patient comment about this appointment', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_comments', to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_comments', to='CareLink.timeslot')),
            ],
            options={
                'verbose_name': 'Appointment Comment',
                'verbose_name_plural': 'Appointment Comments',
                'ordering': ['-created_at'],
                'unique_together': {('timeslot', 'created_by')},
            },
        ),
    ]
