# Generated by Django 5.2.1 on 2025-07-05 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0020_add_appointment_comment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_schedule_changes', models.BooleanField(default=True)),
                ('email_new_tickets', models.BooleanField(default=True)),
                ('email_comments', models.BooleanField(default=True)),
                ('app_enabled', models.BooleanField(default=True)),
                ('app_schedule_changes', models.BooleanField(default=True)),
                ('app_new_tickets', models.BooleanField(default=True)),
                ('app_comments', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('schedule_new', 'New Appointment Scheduled'), ('schedule_confirmed', 'Appointment Confirmed'), ('schedule_cancelled', 'Appointment Cancelled'), ('schedule_modified', 'Appointment Modified'), ('schedule_change_request', 'Schedule Change Requested'), ('ticket_new', 'New Helpdesk Ticket'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_updated', 'Ticket Updated'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_comment', 'New Ticket Comment'), ('demand_new', 'New Service Demand'), ('demand_approved', 'Service Demand Approved'), ('demand_rejected', 'Service Demand Rejected'), ('appointment_comment', 'New Appointment Comment'), ('provider_message', 'Message from Provider'), ('coordinator_message', 'Message from Coordinator'), ('profile_updated', 'Profile Updated'), ('system_announcement', 'System Announcement')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareLink.schedule')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('service_demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareLink.servicedemand')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareLink.enhancedticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='CareLink_no_recipie_a32ccf_idx'), models.Index(fields=['recipient', 'is_read'], name='CareLink_no_recipie_2afd93_idx'), models.Index(fields=['notification_type'], name='CareLink_no_notific_208ff6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('cancel', 'Cancel Appointment'), ('reschedule', 'Reschedule Appointment'), ('modify_time', 'Modify Time Only')], max_length=20)),
                ('current_date', models.DateField()),
                ('current_start_time', models.TimeField()),
                ('current_end_time', models.TimeField()),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('requested_start_time', models.TimeField(blank=True, null=True)),
                ('requested_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('requester_notes', models.TextField(blank=True)),
                ('coordinator_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helpdesk_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CareLink.enhancedticket')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_schedule_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_change_requests', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='CareLink.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', '-created_at'], name='CareLink_sc_request_1689e2_idx'), models.Index(fields=['status'], name='CareLink_sc_status_32795e_idx'), models.Index(fields=['schedule'], name='CareLink_sc_schedul_92057b_idx')],
            },
        ),
    ]
