# Generated by Django 5.2.1 on 2025-07-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0021_notificationpreference_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='servicedemand',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.DeleteModel(
            name='ProvidingCare',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
