# Generated by Django 5.2.1 on 2025-07-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0022_remove_old_emergency_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_address',
            field=models.TextField(blank=True, help_text="Address of the patient's general practitioner", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_email',
            field=models.EmailField(blank=True, help_text="Email address of the patient's general practitioner", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(blank=True, help_text="Name of the patient's general practitioner", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_phone',
            field=models.CharField(blank=True, help_text="Phone number of the patient's general practitioner", max_length=20, null=True),
        ),
    ]
