# Generated by Django migration for INAMI medical care integration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0023_patient_doctor_address_patient_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='inami_data',
            field=models.JSONField(
                blank=True, 
                null=True, 
                help_text="INAMI medical care configuration data including care type, pricing, and codes"
            ),
        ),
    ]
