# Generated by Django 5.2.1 on 2025-07-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0024_add_inami_data_to_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Patient's specific hourly rate for services like family help and housekeeping (€0.94 - €9.97)", max_digits=5, null=True),
        ),
    ]
