# Generated by Django 5.2.1 on 2025-07-07 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0025_add_patient_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hourly_rate',
        ),
        migrations.CreateModel(
            name='PatientServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(decimal_places=2, help_text='Custom price for this patient-service combination', max_digits=6)),
                ('price_type', models.CharField(choices=[('hourly', 'Per Hour'), ('session', 'Per Session'), ('fixed', 'Fixed Price')], default='hourly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about why this price was set', null=True)),
                ('created_by', models.ForeignKey(help_text='Coordinator who set this price', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareLink.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareLink.service')),
            ],
            options={
                'verbose_name': 'Patient Service Price',
                'verbose_name_plural': 'Patient Service Prices',
                'unique_together': {('patient', 'service')},
            },
        ),
    ]
