# Generated by Django 5.2.1 on 2025-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0026_remove_patient_hourly_rate_patientserviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='new_invoice_created_after_contest',
            field=models.BooleanField(default=False, help_text='True if a new invoice was created after contest resolution'),
        ),
    ]
