# Generated by Django 5.2.1 on 2025-07-18 20:12

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0027_invoice_new_invoice_created_after_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfolder',
            name='note',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
