# Generated by Django 5.2.1 on 2025-07-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0028_alter_medicalfolder_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='True if the patient profile has been anonymized for GDPR compliance'),
        ),
    ]
