# Generated by Django 5.2.1 on 2025-07-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0029_patient_is_anonymized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('schedule_new', 'New Appointment Scheduled'), ('schedule_confirmed', 'Appointment Confirmed'), ('schedule_cancelled', 'Appointment Cancelled'), ('schedule_modified', 'Appointment Modified'), ('schedule_change_request', 'Schedule Change Requested'), ('ticket_new', 'New Helpdesk Ticket'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_updated', 'Ticket Updated'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_comment', 'New Ticket Comment'), ('demand_new', 'New Service Demand'), ('demand_approved', 'Service Demand Approved'), ('demand_rejected', 'Service Demand Rejected'), ('appointment_comment', 'New Appointment Comment'), ('provider_message', 'Message from Provider'), ('coordinator_message', 'Message from Coordinator'), ('profile_updated', 'Profile Updated'), ('system_announcement', 'System Announcement'), ('security_alert', 'Security Alert'), ('security_threat_detected', 'Security Threat Detected'), ('admin_access_attempt', 'Admin Access Attempt')], max_length=50),
        ),
    ]
