# Generated by Django 5.2 on 2025-07-21 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0030_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDemandPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='service_demand_prescriptions/%Y/%m/')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document')),
                ('service_demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_files', to='CareLink.servicedemand')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Demand Prescription',
                'verbose_name_plural': 'Service Demand Prescriptions',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
