# Generated by Django 5.2 on 2025-07-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0031_servicedemandprescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedemandprescription',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicedemandprescription',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
