# Generated by Django 5.2.1 on 2025-07-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0033_add_service_demand_update_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimelineEventPatient',
        ),
    ]
