# Generated by Django 5.2 on 2025-07-26 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareLink', '0034_delete_timelineeventpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the verification code expires')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the email was verified', null=True)),
                ('resend_count', models.IntegerField(default=0, help_text='Number of times code was resent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verification',
            },
        ),
    ]
